services:
  gateway-service:
    build: ./gateway-service
    ports:
      - "8088:8088"

  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"

  student-service:
    build: ./student-service
    ports:
      - "8085:8085"

  course-service:
    build: C:\Users\bhsan\OneDrive\Bureau\microservice\project-course
    ports:
      - "8086:8086"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentsdb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
