version: '3.8'

networks:
  my-network:
    driver: bridge

services:
  discovery-server:
    image: discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - my-network
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  config-server:
    image: eclipse-temurin:17-jdk-jammy
    container_name: config-server
    volumes:
      - ./config-repo:/app/config-repo
    working_dir: /app
    command: java -jar config-server.jar
    ports:
      - "8888:8888"
    networks:
      - my-network

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my-network

  student-service:
    image: student-service:latest
    container_name: student-service
    ports:
      - "8085:8085"
    networks:
      - my-network
    depends_on:
      - mysql
      - discovery-server
      - config-server
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.application.name": "student-service",
        "spring.datasource.url": "jdbc:mysql://mysql:3306/studentdb?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.hibernate.ddl-auto": "update",
        "server.port": "8085",
        "eureka.client.service-url.defaultZone": "http://discovery-server:8761/eureka/",
        "spring.config.import": "optional:configserver:http://config-server:8888"
      }'

  course-service:
    image: course-management:latest
    container_name: course-service
    ports:
      - "8082:8082"
    networks:
      - my-network
    depends_on:
      - mongodb
      - discovery-server
      - config-server
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.application.name": "course-service",
        "spring.data.mongodb.uri": "mongodb://mongodb:27017/course-db",
        "server.port": "8082",
        "eureka.client.service-url.defaultZone": "http://discovery-server:8761/eureka/",
        "spring.config.import": "optional:configserver:http://config-server:8888"
      }'

  gateway-service:
    image: gateway-service:latest
    container_name: gateway-service
    ports:
      - "8088:8088"
    networks:
      - my-network
    depends_on:
      - student-service
      - course-service
      - discovery-server
      - config-server
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.application.name": "gateway-service",
        "server.port": "8088",
        "spring.cloud.gateway.routes[0].id": "student-service",
        "spring.cloud.gateway.routes[0].uri": "lb://STUDENT-SERVICE",
        "spring.cloud.gateway.routes[0].predicates[0]": "Path=/api/students/**",
        "spring.cloud.gateway.routes[1].id": "course-service",
        "spring.cloud.gateway.routes[1].uri": "lb://COURSE-SERVICE",
        "spring.cloud.gateway.routes[1].predicates[0]": "Path=/api/courses/**",
        "eureka.client.service-url.defaultZone": "http://discovery-server:8761/eureka/",
        "spring.config.import": "optional:configserver:http://config-server:8888"
      }'
